---

# cloud-init image configuration
image_url: "https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img" # this is the usrl the image will be downloaded from

image_ostype: l26 # image os type is set for linux

# Image location

image_location: /tmp/jammy-server-cloudimg-amd64.img # the location image is saved to (change your own filename, mine was [jammy-server-cloudimg-amd64.img])

# VM template vmid

template_vmid: 6900 # vmid of the template, make sure it's not taken

# cloud-init configuration
ci_user: gurdt55 # user for cloud init machine
ci_password: "{{ ansible_password }}" # password for the cloud init machine

# VM configuration (looped over)
machines:                       ### THESE ARE THE MACHINES CREATED, ADD MORE IF YOU WANT ###
  - name: homeserver.lab
    size: 100G
    cores: 2
    memory: 8192
  - name: game.server
    size: 100G
    cores: 2
    memory: 5500