---
- hosts: pve1
  become: yes

  vars:
    ansible_python_interpreter: /usr/bin/python3

  pre_tasks:
    - name: Include vault
      ansible.builtin.include_vars:
        file: encrypted.yml

  roles:
    # - role: system
    #   vars:
    #     hostname: pve1
    #     update_packages: true
    #     packages:
    #       - sudo
    #       - htop
    - role: ansibleRole-proxmox-templates
      cloudimgs:
        - url: "https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img"
          templateName: ubuntu-20.04-server
          additionalDescription: ""
          templateID: 8000
          user: gurdt55
          ipconfig0: ip=dhcp # ip6=auto,ip=dhcp 
          sshkey: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}" # ssh key that will be added to the user, this should be your public key.
          installAgent: true # if true the proxmox agent will be installed on the VMs
