- name: Disable enterprise repostitory
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    regexp: '^deb https://enterprise.proxmox.com/debian/pve bookworm pve-enterprise'
    line: "deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription"

- name: rename enterprise repo file to non enterprise
  block:
    - name: stat foo
      stat: path=/etc/apt/sources.list.d/pve-enterprise.list
      register: foo_stat

    - name: Move foo to bar
      command: mv /etc/apt/sources.list.d/pve-enterprise.list /etc/apt/sources.list.d/pve-no-sub.list
      when: foo_stat.stat.exists

- name: set ceph repo to community 
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/ceph.list
    regexp: '^deb https://enterprise.proxmox.com/debian/ceph-quincy bookworm enterprise'
    line: 'deb http://download.proxmox.com/debian/ceph-reef bookworm no-subscription'

- name: update packages
  apt:
    upgrade: yes
    update_cache: yes
  ignore_errors: true
  when: update_packages == true

- name: install essential packages
  apt:
    name: "{{ packages }}"
    state: present

- name: echo "unattended-upgrades unattended-upgrades/enable_auto_updates boolean true" | sudo debconf-set-selections  - auto install security updates
  debconf: name=unattended-upgrades question=unattended-upgrades/enable_auto_updates vtype=boolean value='true'

- name: apt install unattended-upgrades
  apt: name=unattended-upgrades

- name: dpkg-reconfigure -f noninteractive unattended-upgrades
  command:
    cmd: dpkg-reconfigure -f noninteractive unattended-upgrades
    creates: /etc/apt/apt.conf.d/20auto-upgradesS
  ignore_errors: true
