- name: update packages
  apt:
    upgrade: yes
    update_cache: yes
  ignore_errors: true

# - name: install essential packages
#   apt:
#     name: "{{ packages }}"
#     state: present

- name: Install pip
  ansible.builtin.apt:
    name:
      - pip
    # update_cache: true
    # install_recommends: false
    state: present

- name: Install proxmoxer
  ansible.builtin.pip:
    name: proxmoxer
    state: present

- name: echo "unattended-upgrades unattended-upgrades/enable_auto_updates boolean true" | sudo debconf-set-selections  - auto install security updates
  debconf: name=unattended-upgrades question=unattended-upgrades/enable_auto_updates vtype=boolean value='true'

- name: apt install unattended-upgrades
  apt: name=unattended-upgrades

- name: dpkg-reconfigure -f noninteractive unattended-upgrades
  command:
    cmd: dpkg-reconfigure -f noninteractive unattended-upgrades
    creates: /etc/apt/apt.conf.d/20auto-upgradesS
