
### ENABLE IF YOU WANT TO CONFIGURE SSH KEYS VIA ANSIBLE ###

- name: Put ssh authorized keys for the user
  ansible.posix.authorized_key:
    user: '{{ username }}'
    state: present
    key: '{{ item }}'
  with_file:
    - /mnt/c/Users/Käyttäjä/.ssh/id_rsa.pub
    - /home/gurdt55/.ssh/id_rsa.pub
  become: true

- name: Disable ssh password login
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#PasswordAuthentication yes"
    line: "PasswordAuthentication no"
  notify: Restart SSHD

#- meta: flush_hand # to force handler execution