---
- name: Check that the cloudinit file exists
  stat:
    path: /tmp/jammy-server-cloudimg-amd64.img
  register: stat_result

- name: Download cloud-init image
  register: image
  ansible.builtin.get_url:
    url: "{{ image_url }}"
    dest: /tmp
    mode: '0644'
    force: true
  when: not stat_result.stat.exists


