- name: update packages
  apt:
    upgrade: yes
    update_cache: yes
  ignore_errors: true

- name: Install pip
  ansible.builtin.apt:
    name:
      - pip
    update_cache: true
    install_recommends: false
    state: present

- name: Install proxmoxer
  ansible.builtin.pip:
    name: proxmoxer
    state: present

- name: Install requests
  ansible.builtin.pip:
    name: requests
    state: present